/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package atividade_pratica_01;

public class Conversor {
    public double celsiusParaFahrenheit(double c) {
        double f = 9 * c / 5 + 32;
        return f;
    }

    public double fahrenheitParaCelsius(double f) {
        double c = (f - 32) * 5 / 9;
        return  c;
    }
}
