/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package atividade_pratica_01;

public class Conversor {
    public double celsiusParaFahrenheit(double c) {
        return 9 * c / 5 + 32;
    }

    public double fahrenheitParaCelsius(double f) {
        return (f - 32) * 5 / 9;
        
    }
}
