/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package entrega_introducao;

import org.junit.Test;
import static org.junit.Assert.*;

public class LibraryTest {
	Conversor conver = new Conversor();
	
    @Test public void converterCelsiusToFahrenheit() {
    	double f = conver.celsiusToFahrenheit(20);
    	assertEquals(68, f);
    }
    
    @Test public void converterFahrenheitToCelsius() {
    	double c = conver.fahrenheitToCelsius(68);
    	assertEquals(20, c);
    }
}