/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package atividade_pratica_01;

public class Conversor {
    //public double celsiusParaFahrenheit() {
       // double f = 9 * c / 5 + 32;
       // return 0;
    //}

    //public double fahrenheitParaCelsius() {
        //double c = (f - 32) * 5 / 9;
    //    return  0;
    //}
}
