/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package atividade_pratica_01;

import org.junit.Test;
import static org.junit.Assert.*;

public class LibraryTest {
        //Considerando as partições de equivalência,
        //Dividimos os casos de testes em classes válidas e Inválidas
        //Teste de classes Inválidas:
        //Função necessita de um parâmetro numero inteiro ou flutuante para a conversão
        //Utilizamos letra para testar:

        @Test public void testPalavra() {
            Conversor convert = new Conversor();
            double results = convert.celsiusParaFahrenheit('a');
            assertEquals(0, results, 0);
        }
    
        //Teste com caractere Coringa:
        @Test public void testCoringa() {
            Conversor convert = new Conversor();
            double results = convert.celsiusParaFahrenheit('@');
            assertEquals(0, results, 0);
        }

        
        //Testes paras Classes válidas:
        //Dada a temperatura 20ºc Celsius o Resultado esperado é 68ºf Fahrenheit
        @Test
        public void testConvertforFahrenheit() {
            Conversor convert = new Conversor();
            double results = convert.celsiusParaFahrenheit(20);
            assertEquals(68, results, 0);
        }
    
        //Dado a temperatura 68ºf fahrenheit o resultado esperado é 20ºc Celsius
        @Test
        public void testConvertforCelsius() {
            Conversor convert = new Conversor();
            double result = convert.fahrenheitParaCelsius(68);
            assertEquals(20, result, 0);
        }
    
}
